context:
  version: "3.3.1"

package:
  name: charasay
  version: ${{ version }}

source:
  url: https://github.com/latipun7/charasay/archive/v${{ version }}.tar.gz
  sha256: d684ac2a43b738e39919051918e4f9d8d5af0b63d79d8afcb248b6228f21c0e0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - chara say "Hello world"

about:
  license: MIT
  license_file:
    - license
    - THIRDPARTY.yml
  summary: The future of cowsay! Colorful characters saying something
  homepage: https://github.com/latipun7/charasay
  repository: https://github.com/latipun7/charasay

extra:
  recipe-maintainers:
    - danielnachun
