context:
  version: "3.3.2"

package:
  name: charasay
  version: ${{ version }}

source:
  url: https://github.com/latipun7/charasay/archive/v${{ version }}.tar.gz
  sha256: f3059fe9ec792b34ab08769d67867ca130196688fd8142ae70ea4a705436e541

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - chara say "Hello world"

about:
  license: MIT
  license_file:
    - license
    - THIRDPARTY.yml
  summary: The future of cowsay! Colorful characters saying something
  homepage: https://github.com/latipun7/charasay
  repository: https://github.com/latipun7/charasay

extra:
  recipe-maintainers:
    - danielnachun
