context:
  version: "3.3.3"

package:
  name: charasay
  version: ${{ version }}

source:
  url: https://github.com/latipun7/charasay/archive/v${{ version }}.tar.gz
  sha256: be0f43d48080d06a6c4bd91d80c22243b2b4acadc38139571d9c1957fb88e193

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - chara say "Hello world"

about:
  license: MIT
  license_file:
    - license
    - THIRDPARTY.yml
  summary: The future of cowsay! Colorful characters saying something
  homepage: https://github.com/latipun7/charasay
  repository: https://github.com/latipun7/charasay

extra:
  recipe-maintainers:
    - danielnachun
